### ISSUE TITLE
Avoid coarse and fine on FIELD value

### ISSUE THREAD

**Issue by christophepersoz** [neu-rah/ArduinoMenu#113]
Hello !

Is there a way to avoid the double editing on FIELD value, coarse and fine replaced by a single edit ?
Maybe it can be automatic if when you enter the same step value on FIELD declaration for coarse and fine, then it switch onto single adjust value mode.

Example,

`
FIELD( _LEDW, "LED COLS ", "", _MINLEDW, _MAXLEDW, 1, 1, doNothing, noEvent, wrapStyle ),
`

That way, when you enter on edit mode, you will have only one click to validate the change as it will skip the coarse adjustment.

Do you think it is possible ?

Thanks a lot

**Comment by neu-rah** [comment]
yes, put zero on fine

**Comment by christophepersoz** [comment]
Brillant and fast as a lightning ! 
Thanks a lot !
