### ISSUE TITLE
how to force menu refresh?

### ISSUE THREAD

**Issue by lfc7** [neu-rah/ArduinoMenu#12]
hello
Can't find the way to force refresh (redraw) of menu, got some "fields" which variables are changing and would like them to appear updated in the menu without need of moving in menus.
thanks

**Comment by neu-rah** [comment]
set menuout "drawn" data member to 0 and then call the menu pool again, ex:
out.drawn=0;
mainMenu.pool(out,allIn);

**Comment by lfc7** [comment]
Yes , so easy !!
Many thanks
