### ISSUE TITLE
esp8266 compilation error (arduino 1.8.5)

### ISSUE THREAD

**Issue by reaper7** [neu-rah/ArduinoMenu#121]
today I update my local copy of this lib from 4.0.1 to current 4.0.6
and I got this error msg:
```
xtensa-lx106-elf-gcc: error: C:\tmp\arduino_build_229612\libraries\ArduinoMenu\ArduinoMenu.a: No such file or directory
``` 
I found that problematic changes have been added with commit https://github.com/neu-rah/ArduinoMenu/commit/5198bb0fed7199b0cf92c9ac2945ec03f194ed7b
more precisely, change inside _library.properties_ -> _dot_a_linkage_ from **false** to **true**

when I change this property to false everything is compiled without errors

**Comment by neu-rah** [comment]
thanks for the feedback, I wonder if the same could be achieved by cleaning up the project...
but anyway I will set it back to false

**Comment by reaper7** [comment]
solved 👍
