### ISSUE TITLE
how to call update function when field update by user

### ISSUE THREAD

**Issue by niijyeni** [neu-rah/ArduinoMenu#131]
updateEvent field values has been updated, this is only used if options->useUpdateEvent=true otherwise enterEvent will be used. (from 3.1.0)

```
result updateSetting(eventMask e,prompt& p){
  saveSetting();
  return proceed;
}

...// other code
FIELD((g_setting.rate_averageCharge), "Average", "c", 0.05, 0.5, 0.02, 0.01, updateSetting, updateEvent, wrapStyle)
...// other code

...// other code
options->useUpdateEvent = true;   <-- compile error 'struct Menu::config' has no member named 'useUpdateEvent'
...// other code
```

please help me

**Comment by neu-rah** [comment]
Hi! Yes documentation is outdated, sorry...

https://github.com/neu-rah/ArduinoMenu#-api-changes

useUpdateEvent option moved to navRoot on version 4
