### ISSUE TITLE
Add a function on SUBMENU call

### ISSUE THREAD

**Issue by christophepersoz** [neu-rah/ArduinoMenu#14]
Hello,

You menu is great to create complex structure and easy debugging/navigation/use, thanks a lot to share it.
Now that I'm much more comfortable with your library, I would like to expand it and add a function on SUBMENU call. Is that possible ? I tried but it seems that is only possible for OP, FIELD and VALUE.
Any track to follow ?
This will allows to launch several actions entering a sub-menu instead of doing it inside the loop by testing the level of the current menu.

Thanks in advance

**Comment by neu-rah** [comment]
you can use a regular function and then use a loop inside of it to poll another menu

**Comment by christophepersoz** [comment]
I tried to replace SUBMENU call by an OP calling a function that poll the SUBMENU which was called before but it result in a mess on display.

**Comment by neu-rah** [comment]
please clear the screen before cycling the second menu

**Comment by neu-rah** [comment]
just added it, now every element can have an associated action
examples of assigning actions:
```c++
submenu.action=trig;//test on submenu
sample_clock.action=trig;//test on choose
onoff_tog.action=trig;//test on toggle
mainMenu.data[1]->action=trig;//test on field
```
regular options already have an associated action, but it can be changed just like a field
