### ISSUE TITLE
Feature request: option->invertNavigation

### ISSUE THREAD

**Issue by daniel-leonard-robinson** [neu-rah/ArduinoMenu#140]
Hi Rui, is it possible to invert the navigation, instead of the FieldKeys?

**Comment by neu-rah** [comment]
Hi!
what is your input method?

**Comment by daniel-leonard-robinson** [comment]
Serial and LiquidCrystal.

I actually found where to implement it. In `nav.cpp`, function ```navCmd navNode::doNavigation(navCmd cmd)```, I just swapped the `downCmd` and `upCmd`, which I'm satisfied with.

It's not urgent, but you can think about it for future releases.
