### ISSUE TITLE
Four buttons on one analog pin

### ISSUE THREAD

**Issue by T94T** [neu-rah/ArduinoMenu#142]
Hi,
I want to attach four buttons (SMD joystick) to one analog pin. Each has another resistor connected to it. So each state (Up, Down, ...) can be recognized by a different analog reading.

I found some comments here in the issues talking about "genericKeyboard.h" Doesn't this file exist anymore? How can I solve my problem?

**Comment by neu-rah** [comment]
Hi!
you might be interested in https://github.com/neu-rah/ArduinoMenu/tree/master/examples/codeCtrl basically lets you drive the menu by sending command to it, allowing virtually any interface.

**Comment by T94T** [comment]
Really cool! This works great. Thanks a lot.
