### ISSUE TITLE
idxCmd does also an enterCmd

### ISSUE THREAD

**Issue by T94T** [neu-rah/ArduinoMenu#145]
It seems that
`navigation.doNav(navCmd(idxCmd, 0));
`also does an enterCmd. I have a sub menu on index 0. Everytime I do a idxCmd 0 the sub menu gets displayed immediately.

**Comment by neu-rah** [comment]
yes, it does
can change selection by setting current navigation level object `navNode::sel` data member
https://github.com/neu-rah/ArduinoMenu/blob/master/src/nav.h#L59

you can obtain current navNode with `navRoot::node()`
https://github.com/neu-rah/ArduinoMenu/blob/master/src/nav.h#L119

**Comment by T94T** [comment]
Thank you for pointing me to nav.h
I found the reset() method which does exactly what I want.
