### ISSUE TITLE
clickEncoder setup

### ISSUE THREAD

**Issue by Ken-Fitz** [neu-rah/ArduinoMenu#151]
I'm trying to integrate the click encoder into a menu but fail miserably 
Its the Timer-based rotary encoder logic by Peter Dannegger which I think you have the include for in your library. Could you put up a simple example in the examples folder. I've looked through all that are there at present and not found one.

**Comment by neu-rah** [comment]
Hi!
just pushed an example that uses clickEncoder (and adafruit TFT), but has the code has two alternative encoders (conditional compile on USE_CLICK_ENCODER defined) it should be clear what the changes are.
https://github.com/neu-rah/ArduinoMenu/blob/master/examples/adafruitGfx/tft/tft/tft.ino

report here if any problem or doubt. you are also welcome to join us at gitter
https://gitter.im/ArduinoMenu/Lobby?utm_source=share-link&utm_medium=link&utm_campaign=share-link
