### ISSUE TITLE
escCmd to return from idle

### ISSUE THREAD

**Issue by evfool** [neu-rah/ArduinoMenu#155]
Currently only the "enterCmd" seems to be able to navigate back to the menu from an idle function. It would be great if this could happen both with enterCmd or escCmd (exit from idle means open menu mode).

**Comment by neu-rah** [comment]
seems ok, missed that myself multiple times. It was an attempt to contain code size.
some devices do not have esc key.

**Comment by neu-rah** [comment]
meanwhile, this code can do what you want externally (loop function) before `nav.poll` or `nav.doInput`

```c++
  if (nav.sleepTask&&serial.peek()=='/') {
    serial.read();//remove the escape otherwise we will enter idle again
    nav.idleOff();
  }
```

nav.sleepTask is NULL when menu working
here i'm peeking serial (my menu input object) and look for '/', to be correct i should look for configured character, but this works

**Comment by evfool** [comment]
Thanks for the suggestion. I'm using a key-based input, so indeed, some devices might not have an esc key, but in that case esc won't return to the previous screen, as they won't be able to press it. If you want, I could come up with a MR with the relevant changes (based on a quick check the two lines I'd also add escCmd as an option would be https://github.com/neu-rah/ArduinoMenu/blob/44ad5a31fbf2add5ec9d181507dea529cee09251/src/nav.cpp#L114 and https://github.com/neu-rah/ArduinoMenu/blob/44ad5a31fbf2add5ec9d181507dea529cee09251/src/nav.cpp#L128 ).

**Comment by neu-rah** [comment]
excellent :D
