### ISSUE TITLE
Using  ST7920 GLCD

### ISSUE THREAD

**Issue by benovitch** [neu-rah/ArduinoMenu#16]
Is I possible to use a GLCD with ST7920 chip with your library? 

Ben

**Comment by neu-rah** [comment]
that depends on the driver you use for it, as this is a graphic lcd I assume its not the standard lcd (that comes with arduino).
The menu system uses some graphic displays (adadruit library based and UTFT
http://www.rinkydinkelectronics.com/library.php?id=50

if its the case that your display drivers is not supported then you just have to derive from class menuOut and implement a couple of functions:

    virtual size_t write(uint8_t) = 0;
    virtual void setCursor(int x,int y)=0;
    virtual void printMenu(menu&,bool drawExit)=0;
    virtual void clearLine(int ln)=0;
    virtual void clear()=0;

and eventually finetune some others like:

    virtual void showCursor() {}
    virtual void hideCursor() {}
    void setCursor(int x)
    virtual void printPrompt(prompt &o,bool selected,int idx,int posY,int width);

the menuOut class is here: https://github.com/neu-rah/ArduinoMenu/blob/master/menu.h
check out and implementation on adafruitGfx driver here: https://github.com/neu-rah/ArduinoMenu/blob/master/menuGFX.h
