### ISSUE TITLE
ClickEncoder issues with counter-clockwise

### ISSUE THREAD

**Issue by ibishop100** [neu-rah/ArduinoMenu#171]
Hi, I've been fighting with an issue with ClickEncoder for a while now.  I am able to get perfect results with the ESP8266 demo from the ClickEncoder repository.  Up, down, click, double click, etc all work fine.

When I wire it up with ArduinoMenu combining a few examples together (since I am using a different screen, and timer method), I get reliable button presses and clockwise events, but not counter-clockwise.  When I scroll CCW, the menu jumps up and right back down to where it was.  If I scroll CCW really quickly, it will scroll up though.

Code attached: [main.txt](https://github.com/neu-rah/ArduinoMenu/files/1878757/main.txt)

Any ideas?

**Comment by ibishop100** [comment]
Was just switching my display driver from SSD1306Ascii to U8G2 and because I have a bug somewhere that's not working, but I found that the encoder works perfectly when the Serial output is the only output.

**Comment by neu-rah** [comment]
checking... thanks for reporting it

**Comment by neu-rah** [comment]
Hi!

i've used this code on esp12e + U8G2 + ssd8266 + clickEncoder.

console outputs encoder pin states
please note that i'm using GPIO pin numbers (https://arduining.com/2015/08/15/nodemcu-esp-12-development-kit-v1-0/)

a note about your encoder timer, please see esp8266 timer usage on my code

```c++
extern "C" {//esp8266 stuff
  #include "user_interface.h"
}

#include <Arduino.h>
#include <ESP8266WiFi.h>

#include <Wire.h>//oled+? bus
#include <U8g2lib.h>//oled driver
// #include <ClickEncoder.h>//from https://github.com/0xPIT/encoder

#define I2C_ADDRESS 0x3C
// #include "SSD1306Ascii.h"
// #include "SSD1306AsciiWire.h"
#include <menu.h>
// #include <menuIO/SSD1306AsciiOut.h>

#include <ClickEncoder.h>
#include <menuIO/clickEncoderIn.h>
#include <menuIO/keyIn.h>
#include <menuIO/chainStream.h>
#include <menuIO/u8g2Out.h>

using namespace Menu;

//monocrome colors
const colorDef<uint8_t> colors[]={
  {{0,0},{0,1,1}},//bgColor
  {{1,1},{1,0,0}},//fgColor
  {{1,1},{1,0,0}},//valColor
  {{1,1},{1,0,0}},//unitColor
  {{0,1},{0,0,1}},//cursorColor
  {{1,1},{1,0,0}},//titleColor
};
#define menuFont u8g2_font_7x13_mf
constexpr int fontX=7;
constexpr int fontY=16;

// SSD1306AsciiWire oled;
#define OLED_ROT U8G2_R2
constexpr int OLED_SDA=0;
constexpr int OLED_SDC=2;
U8G2_SSD1306_128X64_NONAME_F_HW_I2C oled(OLED_ROT, U8X8_PIN_NONE, OLED_SDC, OLED_SDA);

#define encA 5
#define encB 4
#define encBtn 10
#define encSteps 4

ClickEncoder clickEncoder = ClickEncoder(encA,encB,encBtn,encSteps);
ClickEncoderStream encStream(clickEncoder,1);

//----------------------------------------------------------

result doAlert(eventMask e, prompt &item);

result showEvent(eventMask e,navNode& nav,prompt& item) {
  Serial.print("event: ");
  Serial.println(e);
  return proceed;
}

int test=55;

result action1(eventMask e) {
  Serial.print(e);
  Serial.println(" action1 executed, proceed menu");
  Serial.flush();
  return proceed;
}

result action2(eventMask e,navNode& nav, prompt &item) {
  Serial.print(e);
  Serial.println(" action2 executed, quiting menu");
  return quit;
}

int ledCtrl=LOW;

result myLedOn() {
  ledCtrl=HIGH;
  return proceed;
}
result myLedOff() {
  ledCtrl=LOW;
  return proceed;
}

TOGGLE(ledCtrl,setLed,"Led: ",doNothing,noEvent,noStyle //,doExit,enterEvent,noStyle
  ,VALUE("On",HIGH,doNothing,noEvent)
  ,VALUE("Off",LOW,doNothing,noEvent)
);

int selTest=0;
SELECT(selTest,selMenu,"Select",doNothing,noEvent,noStyle
  ,VALUE("Zero",0,doNothing,noEvent)
  ,VALUE("One",1,doNothing,noEvent)
  ,VALUE("Two",2,doNothing,noEvent)
);

int chooseTest=-1;
CHOOSE(chooseTest,chooseMenu,"Choose",doNothing,noEvent,noStyle
  ,VALUE("First",1,doNothing,noEvent)
  ,VALUE("Second",2,doNothing,noEvent)
  ,VALUE("Third",3,doNothing,noEvent)
  ,VALUE("Last",-1,doNothing,noEvent)
);

//customizing a prompt look!
//by extending the prompt class
class altPrompt:public prompt {
public:
  altPrompt(constMEM promptShadow& p):prompt(p) {}
  Used printTo(navRoot &root,bool sel,menuOut& out, idx_t idx,idx_t len,idx_t) override {
    return out.printRaw("special prompt!",len);
  }
};

MENU(subMenu,"Sub-Menu",showEvent,anyEvent,noStyle
  ,OP("Sub1",showEvent,anyEvent)
  ,OP("Sub2",showEvent,anyEvent)
  ,OP("Sub3",showEvent,anyEvent)
  ,altOP(altPrompt,"",showEvent,anyEvent)
  ,EXIT("<Back")
);

MENU(mainMenu,"Main menu",doNothing,noEvent,wrapStyle
  ,OP("Op1",action1,anyEvent)
  ,OP("Op2",action2,enterEvent)
  ,FIELD(test,"Test","%",0,100,10,1,doNothing,noEvent,wrapStyle)
  ,SUBMENU(subMenu)
  ,SUBMENU(setLed)
  ,OP("LED On",myLedOn,enterEvent)
  ,OP("LED Off",myLedOff,enterEvent)
  ,SUBMENU(selMenu)
  ,SUBMENU(chooseMenu)
  ,OP("Alert test",doAlert,enterEvent)
  ,EXIT("<Back")
);

#define MAX_DEPTH 2

constMEM panel panels[] MEMMODE{{0,0,128/fontX,64/fontY}};
navNode* nodes[sizeof(panels)/sizeof(panel)];//navNodes to store navigation status
panelsList pList(panels,nodes,1);//a list of panels and nodes
idx_t tops[MAX_DEPTH]={0,0};//store cursor positions for each level

//define outputs controller
u8g2Out outOLED(oled,colors,tops,pList,fontX,fontY,0,0,3);//,1,3);

// SSD1306AsciiOut outOLED(&oled,tops,pList);//oled output device menu driver
menuOut* outputs[]={&outOLED};//list of output devices
outputsList out(outputs,1);//outputs list

MENU_INPUTS(in,&encStream);

NAVROOT(nav,mainMenu,MAX_DEPTH,in,out);

result alert(menuOut& o,idleEvent e) {
  if (e==idling) {
    o.setCursor(0,0);
    o.print("alert test");
    o.setCursor(0,1);
    o.print("press [select]");
    o.setCursor(0,2);
    o.print("to continue...");
  }
  return proceed;
}

result doAlert(eventMask e, prompt &item) {
  nav.idleOn(alert);
  return proceed;
}

//when menu is suspended
result idle(menuOut &o, idleEvent e) {
  //o.clear();
  switch(e) {
    case idleStart:o.println("suspending menu!");break;
    case idling:o.println("suspended...");break;
    case idleEnd:o.println("resuming menu.");break;
  }
  return proceed;
}

//esp8266 timer
os_timer_t myTimer;
void timerCallback(void *) {clickEncoder.service();}

void setup() {
  Serial.begin(115200);
  while (!Serial) {
    /* code */
  }
  Serial.println();

  delay(3000);

  pinMode(encBtn,INPUT_PULLUP);

  while(!Serial);
  Serial.println("menu 4.x test");
  Serial.flush();
  Wire.begin();
  oled.begin();
  oled.setFont(menuFont);
  // oled.begin(&Adafruit128x64, I2C_ADDRESS);
  // oled.setFont(System5x7);
  // oled.clear();
  // oled.print("Hello world!");
  nav.idleTask=idle;//point a function to be used when menu is suspended
  mainMenu[1].enabled=disabledStatus;
  nav.showTitle=false;

  //encoder timer!
  os_timer_setfn(&myTimer, timerCallback, NULL);//set the callback funtion
  os_timer_arm(&myTimer, 1, true);//setup the timer tick
}

void loop() {
  // static uint32_t lastService = 0;
  // please use timer
  // if (lastService + 1000 < micros()) {
  //   lastService = micros();
  //   clickEncoder.service();
  //
  // }

  //--------------------Menu:------------------------
  constexpr int menuFPS=1000/30;
  static unsigned long lastMenuFrame=-menuFPS;
  unsigned long now=millis();
  if (now-lastMenuFrame>=menuFPS) {
    lastMenuFrame=millis();
    // Serial.write('.');
    Serial.print(digitalRead(encA));
    Serial.print(digitalRead(encB));
    Serial.println(digitalRead(encBtn));
    nav.doInput();
    if (nav.changed(0)||(nav.sleepTask&&nav.idleChanged)) {//gfx device [0] changed?
      oled.setFont(menuFont);
      oled.firstPage();
      do nav.doOutput(); while(oled.nextPage());
    }
  }
}
```

please let me know the outcome, thanks

**Comment by ibishop100** [comment]
Wow, thanks for your efforts!

Same issue, CW works perfectly, CCW is unreliable.  Running the menu with serial output shows the encoder is working with the menu code perfectly though.  Very very odd.

I switched to the encoder library you linked, to no difference.  I have been using the soligen2010 fork as that's what PlatformIO finds for me (and it works out of the box with ESP).

Perhaps it's a hardware issue with the NodeMCUs I'm using?  I seriously doubt they are genuine, perhaps they are causing the issue somehow?

I have some different ESP boards (D1 Mini, and something called a NodeMCU v3).  Will try them this weekend.  Too bad I don't have any different encoders, though they do seem ok when used without the LCD.

[This](https://instudio.mabangapp.com/img/201809/BBM6732/BBM6732g01.jpg) is what the encoder looks like.

Thanks again!

**Comment by ibishop100** [comment]
Well, just tried it with a Wemos D1 Mini, same result.  I have to assume it's some kind of timing issue combined with the encoder I am using.  It's hard to put my finger on, but it doesn't seem consistent either, sometimes works better than others.  Possibly it works better if left alone for a minute?

What encoder are you testing with?  Does it have the pcb or is it just the 5 pin encoder?  I have a couple other encoders on their way, but it will be weeks before they show up.

I'll try the other ESP board I have just in case.

**Comment by neu-rah** [comment]
have and encoder like yours on its way... my current is an old encoder that probably has some small capacitor and i usually add a 330 resistor on the common ground as a precaution. In fact i have a bad encoder and it flicks sometimes, but it flick on both directions.

there is an alternative encoder driver `menuIO/encoderIn.h`

yes, timing is very important for clickEncoder, be sure to use the esp8266 timer.

also check that none of the pins has a led on it and also that the pins are not used by internal hardware such as SPI_CS... well you trying a different board so i think its not the case.

a good test to put your finger on it would be not using the encoder for menu, but use the encoder test code mixed with the menu so that we can tell if there is something activated while running on the menu environment that affects the encoder. Because the same encoder on the same pins works ok while using the encoder test code.

hmm... i do really want to know the cause of this

thanks for your feedback

**Comment by neu-rah** [comment]
any news on this?

**Comment by ibishop100** [comment]
No, sorry.  Has been a very busy week.  Really good suggestions though.

I should have some time this weekend.

**Comment by neu-rah** [comment]
no rush, i was just curious
take your time
and thanks for the quick response :D

**Comment by ibishop100** [comment]
Hi, just a quick note.  I've been waiting for my new encoders to arrive and they did today.  Your code works fine with with the Keyes clone encoder I just received.  This encoder has just two 10k resistors, while the encoder I was having trouble with has 5 resistors and two caps.  I also have some bare encoders I will play with later.

I'm ok with using these new encoders, maybe if you want some of the 'bad' ones, I can send you a couple.  I might try desoldering the extraneous bits from one to make it like the keyes one...  Caps off, no effect.  I'll trace out the resistors later and pull off the ones that don't match.

**Comment by neu-rah** [comment]
Thanks a lot, I do live on a very remote location but if you have a picture of them or a web reference...

living in Azores islands, Portugal :D
guess its cheaper to order a new one from china

**Comment by ibishop100** [comment]
Maybe I should deliver them, looks like an amazing place!  They're not even available on Aliexpress anymore, so possibly a broken product, or something made for a different purpose.

![utb8sssscmnexkjk43ubq6zlppxal](https://user-images.githubusercontent.com/16710282/39666543-2a15537e-505a-11e8-8ce5-ddac6217c34e.jpg)
![utb8tcsscmnexkjk43ubq6zlppxaf](https://user-images.githubusercontent.com/16710282/39666544-2a2f2506-505a-11e8-9c96-f36b69b24d5b.jpg)
![utb8elctcarfxkjk43ovq6ybnpxaw](https://user-images.githubusercontent.com/16710282/39666545-2a458a76-505a-11e8-9239-c70b12aa6093.jpg)

Oh, here they are:  [encoders](http://www.icstation.com/rotary-encoder-module-brick-sensor-development-round-audio-rotating-potentiometer-knob-arduino-p-12273.html)

Still I wouldn't bother.  Worst case I'd just desolder the rotary encoder and use it without the pcb.  I have 10 other ones to use first though..  ;)

**Comment by neu-rah** [comment]
it looks just like the ones that just arrived here, not checked the resistor values or connect them yet

**Comment by neu-rah** [comment]
![enc1](https://user-images.githubusercontent.com/4712642/40280267-1f37c47c-5c40-11e8-910b-c6e598009ee8.png)
![img_20180520_150519](https://user-images.githubusercontent.com/4712642/40280268-1f688bd4-5c40-11e8-8b71-85eb6d6867f3.jpg)

have this ones, done a quick check with clickEncoder and it worked pretty well, guess cliencoder is using internal pull-ups, but not checked to that detail. here's the link: https://www.ebay.com/itm/Rotary-Encoder-Module-Brick-Sensor-Development-Board-Potentiometer-5V/382178758228?ssPageName=STRK%3AMEBIDX%3AIT&_trksid=p2057872.m2749.l2649
