### ISSUE TITLE
SSD1306 Oled using Adafruit_SSD1306.h

### ISSUE THREAD

**Issue by wildview** [neu-rah/ArduinoMenu#191]
Nice work on this. This is probably not a issue, but would like to implement your menu system on a project using an SSD1306 Oled display w/ a Teensy v3.2 device. I need to use the Adafruit_SSD1306 and Adafruit_GFX libs since I need to do some graphics work. Does your menu system support using these Adafruit libs versus the SSD1306Ascii code. If so, do you have an example using the Adafruit_SSD1306 display driver. I'm using a Teensy device, so I have lots of memory =) 

Regards, R

**Comment by neu-rah** [comment]
Hi! thanks for your interest on the lib
The menu library only depends on the graphics lib, so any screen screen that can work with that specific gfx library can in theory be used with the menu
I've been using SSD1306 with u8g2 and it works very nice, using esp8266 and esp32...
we also have this chat room where people use to exchange ideas an some code, you are welcom to join in https://gitter.im/ArduinoMenu/Lobby

**Comment by neu-rah** [comment]
need more help?

**Comment by TamojitSaha** [comment]
Closing due to lack of inactivity.
