### ISSUE TITLE
Recommended way to detect top-level exit was pressed?

### ISSUE THREAD

**Issue by malachib** [neu-rah/ArduinoMenu#20]
Hi, I love the library though I struggle to understand using it sometimes !

What do you recommend for detecting that top-level exit is pressed when using the "canExit=true" mechanism?  I don't need to detect sub-menu exit.

On a side note, my submenus don't seem to be showing "exit", but rather a duplicate of the last submenu entry

**Comment by neu-rah** [comment]
submenus should use canExit, and its a fossil from previous versions.
with the new non blocking mechanism we can suspend resume the menu at will, so we can have any option anywhere that can set a flag causing the menu to not be called (suspended) provided that we have a methos to resume it again.
there are some details on the wiki and other use posts
