### ISSUE TITLE
navRoot::timeOut = menuTimeout; invalid use non-static

### ISSUE THREAD

**Issue by Ken-Fitz** [neu-rah/ArduinoMenu#208]
Basically the title.

Trying to set the menu timeout to a int value of seconds.

**Comment by neu-rah** [comment]
`navRoot` is a class, so you should have an object of that class to set the `timeOut`, on most examples the macros create such object (variable) and call it `nav`, if so the line should be:

```c++
nav.timeOut=n;
```

**Comment by Ken-Fitz** [comment]
Doh.
