### ISSUE TITLE
Anyway to use idle to display changing values

### ISSUE THREAD

**Issue by Ken-Fitz** [neu-rah/ArduinoMenu#209]
Is there a way to use the idle task to display changing values, so that when the menu times out, or you go back it displays a list of values that are changing?

    case idling:
        o.setCursor(0, 0);
        o.print("Controller v4.0");
        for (byte iLoop = 0; iLoop < 4 iLoop++) {
          o.setCursor(0, iLoop + 1);
          o.print(strBank[iLoop]);
        }
        break;

Where strBank[] is changed by the program.

**Comment by neu-rah** [comment]
Hi!
Yes, the menu does not store data, instead it uses references to data already existing on your sketch. So you already have access to the data, but guess you already know that. Only putting this here for future reference.
To signal the menu system that the idle screen need to be redraw to reflect changes you can set `navRoot::idleChanged` to true indide your idle handler

**Comment by neu-rah** [comment]
Just to clarify, you must be wondering why idle isn't continuously called with `idling`, and if so why it exists...
well, some devices require a constant full redraw and that device redraw can take multiple menu draws (raster devices).
Being a minimalist (not on size) system we will only call it when the devices so requires and for the number of times needed.

**Comment by Ken-Fitz** [comment]
Works wonderfully.
