### ISSUE TITLE
Problem with activeMenu

### ISSUE THREAD

**Issue by franzuu** [neu-rah/ArduinoMenu#21]
Hi, I would like to display (overlay) a time function in only selected submenus with the following code:
menuNode::activeMenu;// is the current menu
menuNode::activeMenu->sel;// is the index of selected option (hilited), zero based

But it seems there is no activeMenu (compiler says: error: 'activeMenu' is not a member of 'menuNode').

I am trying to overlay a submenu with this example in my function:
if (menuNode::activeMenu==myMenuName) {
  thenOverlayMyTimeCodeInTopRight :)
}

**Comment by neu-rah** [comment]
the name is activeNode, not activeMenu

    if (menuNode::activeNode==myMenuName) {
        thenOverlayMyTimeCodeInTopRight :)
    }
