### ISSUE TITLE
Not active the second line

### ISSUE THREAD

**Issue by BitnerNN** [neu-rah/ArduinoMenu#22]
Why?
[UTFT_menu_1.txt](https://github.com/neu-rah/ArduinoMenu/files/236822/UTFT_menu_1.txt)

![img_20160426_171117](https://cloud.githubusercontent.com/assets/18680613/14821918/4d62c31e-0bd5-11e6-8cc1-72a235e48e13.jpg)

**Comment by neu-rah** [comment]
because of line 110

    mainMenu.data[1]->enabled = false;
