### ISSUE TITLE
Adding new class TFT_eSPI need some changing

### ISSUE THREAD

**Issue by fa1ke5** [neu-rah/ArduinoMenu#232]
hi, i'm adding some changing in macros.h for correct support new class "TFT_eSPIOut:"
code example
MENU_OUTPUTS(out, MAX_DEPTH
             //,ADAGFX_OUT(gfx,colors,6*textScale,9*textScale,{0,2,14,8},{14,2,14,8})// old variant
             , TFT_eSPI_OUT(gfx, colors, 6 * textScale, 9 * textScale, {3, 2, 16, 8}) //new class, new variant
             , NONE
            );

**Comment by neu-rah** [comment]
Hi! you don't want do a pull request?

**Comment by fa1ke5** [comment]
I do it, but I don't it complete or not

**Comment by neu-rah** [comment]
yes, do a pull request from your fork (with your changes), git will sort out the differences and will report them on the pull request for approval... so don't worry.

**Comment by fa1ke5** [comment]
ok, im try to commit, nice day.

**Comment by neu-rah** [comment]
done, thank you :)

**Comment by ddosoff** [comment]
I search throw the whole project and did not found any example of this macro.

Could you explain parameters of: TFT_eSPI_OUT(gfx, colors, 6 * textScale, 9 * textScale, {3, 2, 16, 8})?

Example will be awesome.

**Comment by fa1ke5** [comment]
Насколько я понимаю в текущей версии вы этот код уже не найдете, там видоизменили макросы, проект несколько продвинулся вперед. Я это добавлял когда прикручивал поддержку TFT_eSPI, на тот момент код поддерживал макросы такого формата.

**Comment by ddosoff** [comment]
This macro still in the master branch https://github.com/neu-rah/ArduinoMenu/blob/master/src/macros.h#L93

But it's hard to understand preprocessor magic for the user who is unfamiliar with the whole library logic.
