### ISSUE TITLE
sdmenu and u8g2 rendering seems wrong

### ISSUE THREAD

**Issue by pcharest2000** [neu-rah/ArduinoMenu#241]
Platform:  Arduino bluebill
My menus are rendered properply but when using the sdmenu plugin the background of certain items are not renderd properly.  I have tried both 
u8g2_font_profont12_mr  and u8g2_font_profont12_tr fonts with diffrent results... please find links to images
In the SD menu using the tr font the unselected text seems partially rendred (some background kept),  using the mr font  the whole background of the text is rendred white.

I
![20190319_174921](https://user-images.githubusercontent.com/5985326/54644949-09f01680-4a71-11e9-99bc-c00a384ebd2a.jpg)
![20190319_174901](https://user-images.githubusercontent.com/5985326/54645009-2ab86c00-4a71-11e9-85db-c4f957fbf6ab.jpg)
![20190319_175040](https://user-images.githubusercontent.com/5985326/54645010-2ab86c00-4a71-11e9-94cd-558a3cf62d21.jpg)
![20190319_174907](https://user-images.githubusercontent.com/5985326/54645011-2ab86c00-4a71-11e9-9e0f-118f0e6bc314.jpg)

Tks for your help and great work

Phil

**Comment by neu-rah** [comment]
thanks for your feedback, images gave me a much more clear picture, I'm not using SDMenu on my projects yet, it's recent and I only tested on serial.
Had one report of this, but now it's clear :+1: 
will give it a try on some u8g2 display, btw, what display is that?

**Comment by pcharest2000** [comment]
The display is à 128x64 st7920 using the spi bus.  Ive also tried. Turnising on and of setbitmapmode of u8g2 on and off to no effect.

**Comment by neu-rah** [comment]
this should solve it, reopen if not

**Comment by hicksan** [comment]
> this should solve it, reopen if not

How was this solved please? I cannot get this function to work, even without a display. The example SDCard.Ino file, without modification, fails during Setup. The standard SD card library examples all work perfectly, with the same hardware setup. Has something in menu.h been modified in recent varsions so it no longer works?
