### ISSUE TITLE
Displaying a bool variable

### ISSUE THREAD

**Issue by mbc99** [neu-rah/ArduinoMenu#242]
Hi there. 
I need to display a bool variable on the main menu. I don't want to modify it, just display it.

I'm using the SSD1306 ASCII with button navigation example.

**Comment by neu-rah** [comment]
you can use any enumerated (SELECT|CHOOSE|TOGGLE) and make it read-only, enumerated fields allow you to choose any text for associated boolean values (ex: Yes|No, On|Off, etc...)

read-only is `enable()`|`disable()`
https://github.com/neu-rah/ArduinoMenu/blob/cf8866b57f04d90e5f85d0b08509cf614f19149b/src/items.h#L47

**Comment by mbc99** [comment]
Thanks :)
