### ISSUE TITLE
How to print special characters (á, e', í, ó, ú,°)?

### ISSUE THREAD

**Issue by ferchinas** [neu-rah/ArduinoMenu#243]
Hello: 
I need to print special characters like accented vowels (á, e', í, ó, ú) and degrees symbol(°).
I'm working with on ESP32 with an 0.96 OLED display controlled with the u8g2 library.
I can do this on the screens outside the menu using the drawUTF8 () method instead of drawStr ().
How could I achieve this within the ArduinoMenu?
Thank you

**Comment by neu-rah** [comment]
yes you can do so with u8g2, use `oled.enableUTF8Print();` on setup it should work.

**Comment by ferchinas** [comment]
This works like a charm.
In case it helps someone else: You have to save the file that contains the character strings with UTF-8 coding.
Thank you very much for the help!
