### ISSUE TITLE
hide main menu

### ISSUE THREAD

**Issue by petanque** [neu-rah/ArduinoMenu#255]
Is it possible to hide the first line containing "main menu" and move the panels up a row?

**Comment by Joennuh** [comment]
Coincidentally this question has just been answered in the Gitter chat at https://gitter.im/ArduinoMenu/Lobby
The answer of @neu-rah was:

> For hiding the menu title you can use noTitle instead of noStyle

**Comment by petanque** [comment]
Thanks, I will ask on Gitter next time I have a question.
