### ISSUE TITLE
bug on graphics on long menus

### ISSUE THREAD

**Issue by schroejahr2** [neu-rah/ArduinoMenu#26]
Hi, i just used your great lib to do some menu actions.

However i noticed a -maybe- bug in your lib. 

i have some long menus, with different options. And as you see on the screenshot there is a displaying bug at "input 6". The appeareance of this bug differs if i change the text in this line, but it is laways present.

Any ideas ? 

screenshot: [https://pl.vc/pt8go](https://pl.vc/pt8go)

code (to reproduce the bug, not the whole project, only the menu code): 

`/***************************************
Arduino generic menu system
GFX menu - unsing adafruit gfx screens
tested on ATmega2560
http://www.r-site.net/?at=//op%5B%40id=%273090%27%5D

Sept. 2014 Rui Azevedo - ruihfazevedo(@rrob@)gmail.com

creative commons license 3.0: Attribution-ShareAlike CC BY-SA
This software is furnished "as is", without technical support, and with no 
warranty, express or implied, as to its usefulness for any purpose.

Thread Safe: No
Extensible: Yes

Adafruit GFX library from:
  https://learn.adafruit.com/adafruit-gfx-graphics-library/overview
Display ST7735 driver
  http://www.adafruit.com/product/358
***/
/******************
Rui Azevedo 2014
ruihfazevedo@rrob@gmail.com
********/
#include <SPI.h>
#include <menu.h>//menu macros and objects
#include "menuFields.h"
//#include <pcint.h>//this is incompatible with software serial (arduino needs an handler!)
#include <quadEncoder.h>//quadrature encoder driver and fake stream
#include <keyStream.h>//keyboard driver and fake stream (for the encoder button)
#include <chainStream.h>// concatenate multiple input streams (this allows adding a button to the encoder)
//#include <menuPrint.h>//Print (Serial) menu
#include <Adafruit_GFX.h>    // Core graphics library
#include <Adafruit_ST7735.h> // Hardware-specific library
#include <menuGFX.h>

#if defined(__AVR_ATmega2560__)
  ///////////////////////////////////////////////////////////////////////////
  //TFT + SD
  //#define sdCS  9//not using SD card
  #define tftCS 10
  #define dc    8
  #define rst   -1
  ////////////////////////////////////////////
  // ENCODER (aka rotary switch) PINS
  #define encA 10
  #define encB 12
  #define encBtn 13
#elif defined(__AVR_ATmega328__) || defined(__AVR_ATmega328P__)
  ///////////////////////////////////////////////////////////////////////////
  //TFT + SD
  //#define sdCS  9//not using SD card
  #define tftCS 10
  #define dc    8
  #define rst   -1
  ////////////////////////////////////////////
  // ENCODER (aka rotary switch) PINS
  #define encA 2
  #define encB 3
  #define encBtn 4
#else
  #error "Uknown pinout"
#endif

Adafruit_ST7735 tft(tftCS, dc, rst);
///////////////////////////////////////////////////////////////////////////
//functions to wire as menu actions

//aux function
void nothing() {}

void setValue(int &value,prompt &p,menuOut &o, Stream &i,const char* text,const char* units="",int sensivity=5,int low=0,int hi=100,int steps=0,void (*func)()=nothing);

volatile unsigned int inputModes[] = {1, 1, 1, 1, 1, 1, 1, 1, 1}; // 0 = off  1 = CYL   2 = EGT
volatile unsigned int temperatureIndicatorEGT[] = {150, 170, 200}; 
volatile unsigned int temperatureIndicatorCYL[] = {150, 170, 200};

/////////////////////////////////////////////////////////////////////////
// MENU DEFINITION
// here we define the menu structure and wire actions functions to it

TOGGLE(inputModes[0],input1,"Input 1 :",
VALUE("OFF",0),
VALUE("EGT",1),
VALUE("CYL",2)
);
TOGGLE(inputModes[1],input2,"Input 2 :",
VALUE("OFF",0),
VALUE("EGT",1),
VALUE("CYL",2)
);
TOGGLE(inputModes[2],input3,"Input 3 :",
VALUE("OFF",0),
VALUE("EGT",1),
VALUE("CYL",2)
);
TOGGLE(inputModes[3],input4,"Input 4 :",
VALUE("OFF",0),
VALUE("EGT",1),
VALUE("CYL",2)
);
TOGGLE(inputModes[4],input5,"Input 5 :",
VALUE("OFF",0),
VALUE("EGT",1),
VALUE("CYL",2)
);
TOGGLE(inputModes[5],input6,"Input 6 :",
VALUE("OFF",0),
VALUE("EGT",1),
VALUE("CYL",2)
);
TOGGLE(inputModes[6],input7,"Input 7 :",
VALUE("OFF",0),
VALUE("EGT",1),
VALUE("CYL",2)
);
TOGGLE(inputModes[7],input8,"Input 8 :",
VALUE("OFF",0),
VALUE("EGT",1),
VALUE("CYL",2)
);
TOGGLE(inputModes[8],input9,"Input 9 :",
VALUE("OFF",0),
VALUE("EGT",1),
VALUE("CYL",2)
);

MENU(EGT,"EGT",
FIELD(temperatureIndicatorEGT[0],"EGT LOW"," C",0,400,10,1,nothing),
FIELD(temperatureIndicatorEGT[1],"EGT HIGH"," C",0,400,10,1,nothing),
FIELD(temperatureIndicatorEGT[2],"EGT CRITICAL"," C",0,400,10,1,nothing)
);

MENU(CYL,"CYL",
FIELD(temperatureIndicatorCYL[0],"CYL LOW"," C",0,400,10,1,nothing),
FIELD(temperatureIndicatorCYL[1],"CYL HIGH"," C",0,400,10,1,nothing),
FIELD(temperatureIndicatorCYL[2],"CYL CRITICAL"," C",0,400,10,1,nothing)
);

MENU(Temperatures,"Temperatures",
  SUBMENU(EGT),
  SUBMENU(CYL)
);

MENU(inputMode,"Input Modes",
SUBMENU(input1),
SUBMENU(input2),
SUBMENU(input3),
SUBMENU(input4),
SUBMENU(input5),
SUBMENU(input6),
SUBMENU(input7),
SUBMENU(input8),
SUBMENU(input9)
);

MENU(Log,"Log",
OP("Op1",nothing),
OP("Op2",nothing),
OP("Op3",nothing)
);

MENU(Time,"Time",
OP("Op1",nothing),
OP("Op2",nothing),
OP("Op3",nothing)
);

MENU(LCD,"LCD",
OP("Op1",nothing),
OP("Op2",nothing),
OP("Op3",nothing)
);

MENU(mainMenu,"Sistema",
  SUBMENU(Temperatures),
  SUBMENU(inputMode),
  SUBMENU(Log),
  SUBMENU(Time),
  SUBMENU(LCD)
);

//the quadEncoder
quadEncoder encoder(encA,encB);//simple quad encoder driver
quadEncoderStream enc(encoder,5);// simple quad encoder fake Stream

//a keyboard with only one key :D, this is the encoder button
keyMap encBtn_map[]={{-encBtn,menu::enterCode}};//negative pin numbers means we have a pull-up, this is on when low
keyLook<1> encButton(encBtn_map);

//multiple inputs allow conjugation of the quadEncoder with a single key keyboard that is the quadEncoder button
Stream* in[]={&enc,&encButton};
chainStream<2> quadEncoder_button(in);

//alternative to previous but now we can input from Serial too...
Stream* in3[]={&enc,&encButton};
chainStream<3> allIn(in3);

//describing a menu output, alternatives so far are Serial or LiquidCrystal LCD
menuGFX gfx(tft);

/////////////////////////////////////////////////////////////////////////
void setup() {
  SPI.begin();
  tft.initR(INITR_BLACKTAB);
  tft.setRotation(4);
  tft.setTextWrap(false);
  tft.setTextColor(ST7735_RED,ST7735_BLACK);
  tft.setTextSize(1);
  gfx.resX*=1;//update resolution after font size change
  gfx.resY*=1;//update resolution after font size change
  tft.fillScreen(ST7735_BLACK);
  tft.print("Menu test on GFX");
  //testing menu limits (not using all the screen)
  //size is within screen limits even after rotation
  //this limits are not constrained, please ensure your text fits
  gfx.maxX=24;
  gfx.maxY=16;
  gfx.bgColor=BLACK;

  pinMode(encBtn, INPUT);
  digitalWrite(encBtn,1);
  
  encoder.begin();

  delay(300);
  tft.fillScreen(BLACK);
}

///////////////////////////////////////////////////////////////////////////////
// testing the menu system
void loop() {
  mainMenu.poll(gfx,allIn);
}
`

I am using an rotary encoder, arduino uno and teh adafruit 1.8 breakout board.

Have a nice day !

**Comment by neu-rah** [comment]
just to check  if its a lib bug or memory problem, can you reduce the menu a bit?
lets say by commenting out  some parts like LOG, LCD, TIME

thanks

**Comment by neu-rah** [comment]
version 2.4 uses flash memory, that might help on long menus
