### ISSUE TITLE
encoder pcint.h is missing

### ISSUE THREAD

**Issue by valsesro** [neu-rah/ArduinoMenu#260]
When trying to compile lcd example, I get this error C:\SPB_DATA\.platformio\lib\ArduinoMenu library_ID1468\src/menuIO/encoderIn.h:13:56: fatal error: pcint.h: No such file or directory . I tried to install AnotherPcintLibrary that is meant in encoderIn.h but get same arror. Files in AnotherPcintLibrary ara named YetAnotherPcInt so It doesn't correspond to pcint.h used in menu library.

**Comment by valsesro** [comment]
When I changed the names of AnotherPcintLibrary to pcint.h, there is another problem 'PCattachInterrupt' was not declared in this scope and 'mixHandler' was not declared in this scope

**Comment by neu-rah** [comment]
what board and IDE are you using?
if on arduino IDE install the libs using the "library manager"

**Comment by neu-rah** [comment]
we are talking of this https://github.com/neu-rah/PCINT library, right?

**Comment by valsesro** [comment]
Thanks, I accidentally used another library, but when I installed provided librarry I always get error lib\PCINT-master\src\pcint.h:62:56: error: 'pcintPinMap' was not declared in this scope

**Comment by valsesro** [comment]
Ok, I got it to work, defining pin map for AtMega32U4. Thank you for all your replies.
