### ISSUE TITLE
How to hide menu title?

### ISSUE THREAD

**Issue by vikulin** [neu-rah/ArduinoMenu#265]
How to hide menu title? I'm using Arduino LCD with 2 line chars (2x16 size). I need to show only menu items without menu title as shown in your video here:

https://youtu.be/W-TRCziF67g?t=4

**Comment by neu-rah** [comment]
`nav.showTitle=false`

usually on your setup function, assuming that your nav. root object is `nav`. This is a dynamic property can be set at runtime (any time)

https://github.com/neu-rah/ArduinoMenu/blob/d2ca6505f76e8b4cf4ce3b3667f2dd9968f1d3c3/src/nav.h#L81

**Comment by vikulin** [comment]
Your product is very useful. Have a good day.

Thank you. Regards.

ср, 4 дек. 2019 г. в 15:12, Rui Azevedo <notifications@github.com>:
