### ISSUE TITLE
[Q] Delay between TOGGLE

### ISSUE THREAD

**Issue by leikoilja** [neu-rah/ArduinoMenu#277]
Hey all. 
Thank you for the amazing library.

I have tried finding it in documentation, but don't seem to find anything about how to make a slight delay between TOGGLE options? 

My problem is that when i press the button it changes the state like 5 times while i hold the button. A slight delay between button press of like 5-10ms would perfectly work here i guess. Instead of me introducing a custom delays is there any configuration option for that?

**Comment by neu-rah** [comment]
Hi!

I avoid that by limiting the times that `.poll` is called per second

10 times = 100ms delay

**Comment by leikoilja** [comment]
Ou, that's a good suggestion. Thank you, @neu-rah. 
Could you please share a quick reference how to do it?

**Comment by neu-rah** [comment]
of course, ex: inside loop doing a minimal delay of 100ms, this wont be correct near millis overflow (that happens about every 5 days, but you get the point)

```c++
static unsigned int next=0;
if (millis()>=next) {
  nav.poll();
  next+=millis()+100;
}
```

_please note that I've not compiled this_

**Comment by leikoilja** [comment]
Thank you, @neu-rah, for help! :+1:
