### ISSUE TITLE
Issue with ESP32 Clickencodertft.ino

### ISSUE THREAD

**Issue by timmcarson** [neu-rah/ArduinoMenu#280]
I am trying to use the ESP32 Clickencodertft.ino example from #256 

I am using PlatformIO running on vscode.  when I try to compile I get errors surrounding the ClickEncoder library.

This is what the errors look like
![Capture](https://user-images.githubusercontent.com/62730395/77714097-94395780-6fae-11ea-8c29-14b186b180bc.PNG)

Any help is appreciated

Timm

**Comment by neu-rah** [comment]
Hi!

Thanks for reporting it.

reorder could be  a warning or silenced and it would still work, that initialization is not order dependent. I will try to put it on proper order using vscode or activate the warning on atom+platformio....

meanwhile you might want to look at codeCtrl example (https://github.com/neu-rah/ArduinoMenu/issues/278#issuecomment-604662371) it allow you to use any input method and dont stay dependent of clickEncoder.

**Comment by neu-rah** [comment]
Please note that order error are from clickEncoder lib, not that is wrong, it should be a warning at most, but your compile options vscode+platformio are adding an `-Werror=order` into the compiler options.

My atom+ platformio are also doing the same for esp32. I was able to compile by disabling it as an error and also added some warning suppress for a quiet compile (optional)

added this line to platformio.ini
```ini
build_flags = -Wno-comment -Wno-reorder -Wno-strict-aliasing -Wno-builtin-macro-redefined -Wno-switch
build_unflags = -Werror=reorder
```

**Comment by timmcarson** [comment]
Adding the lines to the platformio.ini file did the trick it compiles now. 

Thanks for the quick response

**Comment by neu-rah** [comment]
https://github.com/espressif/arduino-esp32/issues/3854
