### ISSUE TITLE
License compatibility issue

### ISSUE THREAD

**Issue by pat1** [neu-rah/ArduinoMenu#289]
I suspect it could be some problems of compatibility with your non commercial use license.
If I am not wrong there are possibility we cannot link this library with some other library with license that is not compatible with non commercial clause as for GPL license.

https://fedoraproject.org/wiki/Licensing:Main?rd=Licensing#Bad_Licenses_3
Creative Commons NonCommercial, any version (#CC-BY-NC)
"This license does not qualify as free, because there are restrictions on charging money for copies. "

As for Covid19 there are any possibility to "relax" your software license to a  Open Source License for example with one approved by Open Source Initiative  https://opensource.org/licenses ?

I am a developer and I use GPL license for some libraries and project and I want contribute and use your library.

**Comment by neu-rah** [comment]
Thanks for enlighten me.
would LGPLv2+ be ok?

**Comment by pat1** [comment]
Thank you for making yourself available.
 LGPLv3+ should be ok.
If you want more compatibilities LGPLv2.1+ is the more compatible.
avr arduino core and esp8266 arduino core for example use GNU Lesser General Public License v2.1
https://github.com/esp8266/Arduino/blob/master/LICENSE

License compatibility is like a scienze:
https://fedoraproject.org/wiki/Licensing:Main?rd=Licensing#GPL_Compatibility_Matrix

**Comment by neu-rah** [comment]
done it, LGPL-2.1+

**Comment by pat1** [comment]
perfect!
