### ISSUE TITLE
Issues with U8G2 and Offset Panel

### ISSUE THREAD

**Issue by lucamarrochi** [neu-rah/ArduinoMenu#291]
Hello,

I've put down a little example of ArduinoMenu using 256x64 pixels with U8G2 renderer. I would like to use a panel that has offset in X and Y, as defined below:
`#define fontName u8g2_font_5x7_tf
  #define fontX 5
  #define fontY 9
  #define offsetX 10
  #define offsetY 10
  #define U8_Width 200
  #define U8_Height 54
  U8G2_SSD1322_NHD_256X64_F_4W_HW_SPI u8g2(U8G2_R0, /* cs=*/ U8_CS, /* dc=*/ U8_DC, /* reset=*/ U8_RST);`

The menu is very simple:
`MENU(mainMenu, "Blink menu", Menu::doNothing, Menu::noEvent, Menu::wrapStyle
  ,FIELD(timeOn,"On","ms",0,1000,10,1, Menu::doNothing, Menu::noEvent, Menu::noStyle)
  ,FIELD(timeOff,"Off","ms",0,10000,10,1,Menu::doNothing, Menu::noEvent, Menu::noStyle)
  ,EXIT("<Back")
);`

I got an issue with visualization: on the left side of the menu (when offset is specified) there is an unwanted pipe as you can see from images. They are located at offsetX-1. The pipe is present also on menu title at the same position.

![2](https://user-images.githubusercontent.com/64577630/80691481-9e300800-8ad0-11ea-86a1-173d8e4ae21a.jpg)

![1](https://user-images.githubusercontent.com/64577630/80691596-c7509880-8ad0-11ea-84c2-882dd5cb5bb5.jpg)

**Comment by neu-rah** [comment]
Hi

that offset if for adjusting the font margin, you should set it to remove the pipe.

an example of panels (menu position) as defined here:
https://github.com/neu-rah/ArduinoMenu/blob/master/examples/U8G2/U8G2/U8G2.ino#L188

```c++
U8G2_OUT(u8g2,colors,fontX,fontY,offsetX,offsetY,{0,0,U8_Width/fontX,U8_Height/fontY})
```
this is the panel definition in character coordinates (size depends on chosen font)
```c++
{0,0,U8_Width/fontX,U8_Height/fontY}
```
you should change the 0,0 (x,y) and set the width height accordingly.

please note that u8g2 menu driver will not respect the right margin to solve UTF8 issues, so its up to you to not define extensive content.

you can also specify multiple panels, menu will use them whenever possible (submenus and preview), by specifying a list of panels

`{{x0,y0,w0,h0},{x1,y1,w1,h1},...}`

hope that helps

**Comment by lucamarrochi** [comment]
Thank you for the reply.
I've tried two different configuration:

`#define fontName u8g2_font_5x7_tf
  #define fontX 5
  #define fontY 9
  #define offsetX 0
  #define offsetY 0
  #define U8_Width 200
  #define U8_Height 54
  U8G2_SSD1322_NHD_256X64_F_4W_HW_SPI u8g2(U8G2_R0, /* cs=*/ U8_CS, /* dc=*/ U8_DC, /* reset=*/ U8_RST);

MENU_OUTPUTS(out,MAX_DEPTH
  ,U8G2_OUT(u8g2,colors,fontX,fontY,offsetX,offsetY,{10/fontX,10/fontY,U8_Width/fontX,U8_Height/fontY})
  ,SERIAL_OUT(Serial)
);`

and

`#define fontName u8g2_font_5x7_tf
  #define fontX 5
  #define fontY 9
  #define offsetX 10
  #define offsetY 10
  #define U8_Width 200
  #define U8_Height 54
  U8G2_SSD1322_NHD_256X64_F_4W_HW_SPI u8g2(U8G2_R0, /* cs=*/ U8_CS, /* dc=*/ U8_DC, /* reset=*/ U8_RST);

MENU_OUTPUTS(out,MAX_DEPTH
  ,U8G2_OUT(u8g2,colors,fontX,fontY,offsetX,offsetY,{0,0,U8_Width/fontX,U8_Height/fontY})
  ,SERIAL_OUT(Serial)
);`

But I get the same result. My aim is to have only one panel, aligned to the right side of the display. I would like to use the left part of the display to render other informations not related to the menu.

**Comment by neu-rah** [comment]
please use just integers char pos x,y as menu driver will already account for font size

ex:
`{2,2,U8_Width/fontX-2,U8_Height/fontY-2}`

**Comment by lucamarrochi** [comment]
Using:
```
#define fontName u8g2_font_5x7_tf
  #define fontX 5
  #define fontY 9
  #define offsetX 0
  #define offsetY 0
  #define U8_Width 200
  #define U8_Height 54
```

```
MENU_OUTPUTS(out,MAX_DEPTH
  ,U8G2_OUT(u8g2,colors,fontX,fontY,offsetX,offsetY,{2,2,U8_Width/fontX-2,U8_Height/fontY-2})
  ,SERIAL_OUT(Serial)
);
```

I  see different offset but same result
![3](https://user-images.githubusercontent.com/64577630/80708794-86667d00-8aec-11ea-9003-0bbe0a4b8932.jpg)

**Comment by neu-rah** [comment]
I will check this. Hope that I can duplicate it on similar display...
I will give some feedback as soon as possible
Thanks for reporting

**Comment by neu-rah** [comment]
this is great because i have this display, thank you
definitely something is wrong there.

**Comment by neu-rah** [comment]
looks good, wana submit a PR?

**Comment by lucamarrochi** [comment]
it's ok, wich branch should I use?

**Comment by neu-rah** [comment]
Master branch please
that menu looks really nice!
and i like the positioning, can i use this image as an example?
thank you.

**Comment by lucamarrochi** [comment]
Sure you can use the image!
I have to find what is wrong with the rendering of the rectangle when in "< Back" position of the menu. The only difference is that's is an "EXIT" entry in the menu.

**Comment by neu-rah** [comment]
Thank you! https://github.com/neu-rah/ArduinoMenu/pull/292
please reopen if needed

**Comment by NoObjective** [comment]
> In the meantime, I've found another strange behavior related to panel offset: The panel of the menu is right justify, and I draw a 20x20pixels frame in the left part. Scrolling the menu is ok until you reach EXIT entry. In that case the frame disappear. 


I also have this problem, any solution?
