### ISSUE TITLE
CHOOSE submenu draw & behavior?

### ISSUE THREAD

**Issue by TomaTLAB** [neu-rah/ArduinoMenu#30]
The "CHOOSE" submenu has a "hiden" non selelectable menu-item at bottom of menu if the value list contains number of members less than .maxY and has a doubled, also non selectale item if more or equal. 
Is it a bug? 
And a second question. How I can add an "Exit" option to the "Choose" submenu? 
I suspect that these two questions are interdependent :)

**Comment by TomaTLAB** [comment]
I use menuUTFT.h as an output.

**Comment by neu-rah** [comment]
probably a bug and probably related :D
i will take a look, thanks

**Comment by neu-rah** [comment]
guess i got it, please reopen if persistent

https://github.com/neu-rah/ArduinoMenu/releases/tag/v2.2
