### ISSUE TITLE
Combining Events error on PlatformIO

### ISSUE THREAD

**Issue by HamidSaffari** [neu-rah/ArduinoMenu#321]
Hi, in platformIO when I combining two or more Events compiler got error. 
althogh in Arduino IDE have got no error.

here is the Error:
`
src\code.cpp:396:115: error: invalid conversion from 'int' to 'Menu::eventMask' [-fpermissive]
  396 |   ,FIELD(TEMP_value,"TEMP","",0,16383,10,1,do_TEMP_OUT, enterEvent | exitEvent | updateEvent,wrapStyle)`

**Comment by neu-rah** [comment]
hi!
you can cast the combined to `eventMask`
ie:
```c++
(eventMask)(enterEvent | exitEvent | updateEvent)
```

_not compiled this.. but it should be something like that_

**Comment by HamidSaffari** [comment]
Thanks man.
It works.
 `, (Menu::eventMask)(enterEvent | updateEvent) , `
