### ISSUE TITLE
define two whole different menus at the same project

### ISSUE THREAD

**Issue by HamidSaffari** [neu-rah/ArduinoMenu#329]
Hi and best regard.
How we can define two complete menus and with different navigation and activate each one by two different keys for example?

**Comment by olikraus** [comment]
By writing software or by using a full featured menu system.

**Comment by neu-rah** [comment]
here an example of concurrent menus, https://github.com/neu-rah/ArduinoMenu/blob/master/examples/concurrent/concurrent/concurrent.ino

you can have multiple independent menus and switch between them or have them running at same time provided that they have independent IO, as @olikraus  pointed, it won't be automatic, you must either switch focus between them (calling poll) or do the proper setup for independent IO

**Comment by HamidSaffari** [comment]
Thanks @neu-rah, your example (concurrent.ino) was completely helpful.
