### ISSUE TITLE
TFT_eSPI AND FreeFont

### ISSUE THREAD

**Issue by Koxx3** [neu-rah/ArduinoMenu#344]
Hello,

thanks for yhis wonderful lib !

I use the TFT_eSPI lib and I'd like to use freeFonts.

With standard font, no issue ...
![20210208_231457](https://user-images.githubusercontent.com/11454444/107288415-b4a5bf80-6a63-11eb-8820-41b534e48524.jpg)

With a custom font, the menu is not displayed correctly :
![20210208_231417](https://user-images.githubusercontent.com/11454444/107288429-ba030a00-6a63-11eb-8908-d0612505fedf.jpg)

Any idea why and how to solve this ?

Thanks !

**Comment by Koxx3** [comment]
FIY, I started with this sample :
https://github.com/neu-rah/ArduinoMenu/blob/master/examples/adafruitGfx_eTFT/TFT_eSPI/ArduinoMenu_LilyGo_TTGO_T-display_demo/ArduinoMenu_LilyGo_TTGO_T-display_demo.ino

**Comment by neu-rah** [comment]
Hi, please change https://github.com/neu-rah/ArduinoMenu/blob/master/examples/adafruitGfx_eTFT/TFT_eSPI/ArduinoMenu_LilyGo_TTGO_T-display_demo/ArduinoMenu_LilyGo_TTGO_T-display_demo.ino#L250

to match you font character size

**Comment by Koxx3** [comment]
ok, it worked ;)
thanks !
