### ISSUE TITLE
BUG, The display doesn't change when changing (press rotary encoder) submenu of the toggle

### ISSUE THREAD

**Issue by kevinpt97** [neu-rah/ArduinoMenu#352]
Hello Sir, there is a bug in the 2002 LCD display. The display does not change when changing (press rotary encoder) submenu of the toggle. If on a serial monitor, that's normal.

I am using Arduino Mega.

This is the display on the serial monitor:
https://user-images.githubusercontent.com/42960459/114934921-c1300500-9e64-11eb-83ed-85d4f60d3e92.mp4

But that's not normal on LCD2002, the display doesn't change.

This is the display on LCD 2002:
https://user-images.githubusercontent.com/42960459/114977967-c4ea7880-9eb2-11eb-9d55-03c04fb27c4c.mp4

The display changes when the cursor moves

**Comment by neu-rah** [comment]
hi!
it looks like and encoder issue, can you show your menu input definition?

**Comment by kevinpt97** [comment]
I apologize for taking this as a BUG, after studying your library the problem is found here.

`nav.target-> dirty = true;`

I put that into the function, and it got solved
