### ISSUE TITLE
v2.3 do not build

### ISSUE THREAD

**Issue by christophepersoz** [neu-rah/ArduinoMenu#37]
Hello !

Can you tell me if the 2.3 can be build out of the box with the U8Glib.ino I sent you ? I'm getting a lot of error linked to promptAction() and prompt() from menu.h

So, I'm going back to 2.2 at this time.

Otherwise, I tried to figure it out what's going on with FIELD() in edit mode (refresh issues), without any success - did you find something relevant on your side?

Thanks

**Comment by neu-rah** [comment]
I've changed all action functions from returning void to returning bool.
false=continue
true=quit the menu

**Comment by neu-rah** [comment]
revised examples on 2.3 -> updated
