### ISSUE TITLE
Error while compiling ClickEncoder for ESP32

### ISSUE THREAD

**Issue by Airji3d** [neu-rah/ArduinoMenu#385]
I get an AVR/io.h not found error when I compile the ESP32 Clickencoder example. I don't understand why the Clickencoder.h loads these AVR includes.
Thanks for looking,
Rolland

**Comment by Airji3d** [comment]
Seems that commenting the AVR includes might resolve the error, I need to try this. Found this in #210

**Comment by neu-rah** [comment]
got some similar cases with esp's, please reopen if not fixed.
