### ISSUE TITLE
FIELD menu usage

### ISSUE THREAD

**Issue by szepnorbee** [neu-rah/ArduinoMenu#54]
Hi! Thanks for this avesome library! It works very well, but i can not use Numeris Fields. 
My code is at: **github.com/szepnorbee/Menu_test/tree/master/menu_test_4**

When i compile it i get an error:
variable 'menuField<unsigned char> _menuField8' has initializer but incomplete type

I do not understand what I was doing wrong. Thank you for your help and sorry for my bad english.

**Comment by neu-rah** [comment]
missing include
```c++
#include <menuFields.h>
```
