### ISSUE TITLE
pcint and softwareserial

### ISSUE THREAD

**Issue by shinrayi** [neu-rah/ArduinoMenu#83]
Is there a way to be able to use both libaries? I want to be able to use adafruits gps with an rotary encoder

**Comment by neu-rah** [comment]
pcint is only used by encoderIn.h, however there is also a clickEncoderIn.h that does not use pcint. I think its based on this driver https://github.com/0xPIT/encoder

**Comment by shinrayi** [comment]
i'm trying to get the menu to work with the clickEncoderIn, but i don't understand how to get started. With the encoderIn i could use 
encoderIn<encA,encB> encoder;
encoderInStream<encA,encB> encStream(encoder,4)
to define the pins, but how do i do this with the clickEncoderIn
