### ISSUE TITLE
Streaming.h (and hence ArduinoMenu) conflict with SdFat.h

### ISSUE THREAD

**Issue by BennehBoy** [neu-rah/ArduinoMenu#89]
See here -> https://forum.arduino.cc/index.php?topic=374550.0

Using SdFat would greatly simplify my project (very simple to do datalogging), but this error results if I include the library:

```
error: previous declaration of 'ostream& endl(ostream&)'

 inline ostream& endl(ostream& os) {

                 ^

exit status 1
```

Do you have any suggestions of a workaround?

**Comment by neu-rah** [comment]
that can be fixed

**Comment by BennehBoy** [comment]
Will that need changes to the menu system, or is it something I can do myself - I'm not really a software guy! :-)

**Comment by neu-rah** [comment]
it has to do with streaming, or the lack of them and me implementing streams on the menu.

I think i use them for debug... but have to check first if its not used outside debug, i can use normal printing if i find any on non debug code.

for a quick try you can just comment the lines and see if the compiler complains about it (probably not) even if it is used, it will use the existing. i guess :D

**Comment by BennehBoy** [comment]
These are the fatal ones:

`In file included from C:\Users\bennehboy\Documents\Arduino\LRDuino\LRduinoV0.01\LRDuino\LRDuino.ino:12:0:

C:\Users\bennehboy\Documents\Arduino\libraries\ArduinoMenu\src/menu.h: In member function 'Menu::menuOut& Menu::navRoot::printPath(Menu::menuOut&) const':

C:\Users\bennehboy\Documents\Arduino\libraries\ArduinoMenu\src/menu.h:487:39: error: no match for 'operator<<' (operand types are 'Menu::menuOut' and 'char')

           for(idx_t n=0;n<level;n++) o<<'/'<<path[n].sel;

		   
C:\Users\bennehboy\Documents\Arduino\libraries\ArduinoMenu\src/menu.h: In instantiation of 'Menu::idx_t Menu::menuField<T>::printTo(Menu::navRoot&, bool, Menu::menuOut&, Menu::idx_t, Menu::idx_t) [with T = int; Menu::idx_t = signed char]':

C:\Users\bennehboy\Documents\Arduino\LRDuino\LRduinoV0.01\LRDuino\LRDuino.ino:1173:1:   required from here

C:\Users\bennehboy\Documents\Arduino\libraries\ArduinoMenu\src/menu.h:546:12: error: no match for 'operator<<' (operand types are 'Menu::menuOut' and 'char')

         out<<((root.navFocus==this&&sel)?(tunning?'>':':'):' ');



C:\Users\bennehboy\Documents\Arduino\libraries\ArduinoMenu\src/menu.h: In instantiation of 'void Menu::menuField<T>::printValue(Menu::menuOut&) const [with T = int]':

C:\Users\bennehboy\Documents\Arduino\LRDuino\LRduinoV0.01\LRDuino\LRDuino.ino:1173:1:   required from here

C:\Users\bennehboy\Documents\Arduino\libraries\ArduinoMenu\src/menu.h:143:54: error: no match for 'operator<<' (operand types are 'Menu::menuOut' and 'const int')

         void printValue(menuOut& o) const override {o<<reflex;}



C:\Users\bennehboy\Documents\Arduino\libraries\ArduinoMenu\src/menu.h: In instantiation of 'void Menu::menuField<T>::printHigh(Menu::menuOut&) const [with T = int]':

C:\Users\bennehboy\Documents\Arduino\LRDuino\LRduinoV0.01\LRDuino\LRDuino.ino:1173:1:   required from here

C:\Users\bennehboy\Documents\Arduino\libraries\ArduinoMenu\src/menu.h:144:53: error: no match for 'operator<<' (operand types are 'Menu::menuOut' and 'int')

         void printHigh(menuOut& o) const override {o<<high();}



C:\Users\bennehboy\Documents\Arduino\libraries\ArduinoMenu\src/menu.h: In instantiation of 'void Menu::menuField<T>::printLow(Menu::menuOut&) const [with T = int]':

C:\Users\bennehboy\Documents\Arduino\LRDuino\LRduinoV0.01\LRDuino\LRDuino.ino:1173:1:   required from here

C:\Users\bennehboy\Documents\Arduino\libraries\ArduinoMenu\src/menu.h:145:52: error: no match for 'operator<<' (operand types are 'Menu::menuOut' and 'int')

         void printLow(menuOut& o) const override {o<<low();}

 
C:\Users\bennehboy\Documents\Arduino\libraries\ArduinoMenu\src/menu.h: In instantiation of 'Menu::idx_t Menu::menuVariant<T>::printTo(Menu::navRoot&, bool, Menu::menuOut&, Menu::idx_t, Menu::idx_t) [with T = bool; Menu::idx_t = signed char]':

C:\Users\bennehboy\Documents\Arduino\LRDuino\LRduinoV0.01\LRDuino\LRDuino.ino:1173:1:   required from here

C:\Users\bennehboy\Documents\Arduino\libraries\ArduinoMenu\src/menu.h:641:10: error: no match for 'operator<<' (operand types are 'Menu::menuOut' and 'char')

       out<<(this==&root.active()?':':' ');`

There are also multiple notes pertaining to no known conversions

**Comment by BennehBoy** [comment]
That's without sdfat included, with it included the errors are similar:

```
C:\Users\bennehboy\Documents\Arduino\libraries\ArduinoMenu\src/menu.h: In member function 'Menu::menuOut& Menu::navRoot::printPath(Menu::menuOut&) const':

C:\Users\bennehboy\Documents\Arduino\libraries\ArduinoMenu\src/menu.h:487:39: error: no match for 'operator<<' (operand types are 'Menu::menuOut' and 'char')

           for(idx_t n=0;n<level;n++) o<<'/'<<path[n].sel;
```

**Comment by neu-rah** [comment]
this sdfat?
https://github.com/greiman/SdFat

**Comment by neu-rah** [comment]
on menu.h file replace the Streaming include with:
```c++
  #if !defined(ArduinoStream_h)
    #include <Streaming.h>
  #endif
```

and some lines after th edefinition of endl should be:

```c++
    #if !defined(ARDUINO_STREAMING) || !defined(ArduinoStream_h)
      #define endl "\r\n"
    #endif
```

it compile here ok with sdfat... and will include on next push if it works ok

**Comment by BennehBoy** [comment]
Thanks, I'll try it after work :thumbsup:

**Comment by BennehBoy** [comment]
I'm afraid I still get errors.

If I include sdfat.h prior to the menus:

```
In file included from C:\Users\bennehboy\Documents\Arduino\LRDuino\LRduinoV0.01\LRDuino\LRDuino.ino:12:0:

C:\Users\bennehboy\Documents\Arduino\libraries\ArduinoMenu\src/menu.h: In member function 'Menu::menuOut& Menu::navRoot::printPath(Menu::menuOut&) const':

C:\Users\bennehboy\Documents\Arduino\libraries\ArduinoMenu\src/menu.h:489:39: error: no match for 'operator<<' (operand types are 'Menu::menuOut' and 'char')

           for(idx_t n=0;n<level;n++) o<<'/'<<path[n].sel;
```

If I include the menus first:

```
In file included from C:\Users\bennehboy\Documents\Arduino\LRDuino\LRduinoV0.01\LRDuino\LRDuino.ino:12:0:

C:\Users\bennehboy\Documents\Arduino\libraries\ArduinoMenu\src/menu.h:35:20: error: expected unqualified-id before string constant

       #define endl "\r\n"

                    ^

```

There are more but I've just copied the first occurrences.  I've checked that I have the latest master versions of the repo's for both.

Here's the top of menu.h with the changes: (google seems to think the 2nd error is down to a missing semi-colon somewhere?)

```
#ifndef RSITE_ARDUINO_MENU_SYSTEM
  #define RSITE_ARDUINO_MENU_SYSTEM
  #include <Arduino.h>
  #if !defined(ArduinoStream_h)
    #include <Streaming.h>
  #endif
  #include "menuBase.h"
  #include "shadows.h"

  namespace Menu {

    static const char* numericChars="0123456789.";

    #define _MAX(a,b) (((a)>(b))?(a):(b))
    //#if defined(ESP8266)
    //#if !defined(endl)
    #if !defined(ARDUINO_STREAMING) || !defined(ArduinoStream_h)
      #define endl "\r\n"
    #endif

```

**Comment by neu-rah** [comment]
the top here
```c++
#ifndef RSITE_ARDUINO_MENU_SYSTEM
  #define RSITE_ARDUINO_MENU_SYSTEM
  #include <Arduino.h>
  #if !defined(ArduinoStream_h)
    #include <Streaming.h>
  #endif
  #include "menuBase.h"
  #include "shadows.h"

  namespace Menu {

    static const char* numericChars="0123456789.";

    #define _MAX(a,b) (((a)>(b))?(a):(b))
    //#if defined(ESP8266)
    //#if !defined(endl)
    #if !defined(ARDUINO_STREAMING) || !defined(ArduinoStream_h)
      #define endl "\r\n"
    #endif
```

**Comment by neu-rah** [comment]
they seem identical and i'm compiling here.. for uno/nano with SdFat

**Comment by neu-rah** [comment]
be sure to include sdfat before the menu.h

**Comment by BennehBoy** [comment]
Yes I thought it might be an stm32 so I've tested it within codectrl against an uno - with sdfat included before menu.h and I get the same error.

I recloned sdfat, streaming, and checked arduinmenu - only changes are those you suggested :(

What else could be different/causing this?

**Comment by neu-rah** [comment]
well i have some other changes here because this is my dev version, i will try to make a functional version and push it... will let you know

**Comment by BennehBoy** [comment]
I suspect it's more likely to be something my side

**Comment by neu-rah** [comment]
this last error

In file included from C:\Users\bennehboy\Documents\Arduino\LRDuino\LRduinoV0.01\LRDuino\LRDuino.ino:12:0:

C:\Users\bennehboy\Documents\Arduino\libraries\ArduinoMenu\src/menu.h:35:20: error: expected unqualified-id before string constant

       #define endl "\r\n"

means the #if directive had no success on skiping the endl definition, because SdFat also defines it and probably as a string the code end up something like 

#define "\r\n" "\r\n"

that is not legal

i've checked the sdfat library and they define ArduinoStream_h here:

https://github.com/greiman/SdFat/blob/bc32f5afdd35f8344cc6953c99287b3dc4255667/SdFat/src/FatLib/ArduinoStream.h#L21

but yours seem to not... also i'm using atom+platformio, will check on arduino ide 1.6 or 1.8

**Comment by BennehBoy** [comment]
Line 20/21 of same file on my hdd:

```
#ifndef ArduinoStream_h
#define ArduinoStream_h
```

I recloned the library earlier today to be sure...

**Comment by neu-rah** [comment]
i'm just including <SdFat.h> but not using it, maybe if i initialize the lib... 

arduino ide 1.6 also compiling ok with just the SdFat include, i've pushed my current code to branch dev on ArduinoMenu

**Comment by BennehBoy** [comment]
This is the only reference to endl that I can find in the sdfat src code:

SdFat\src\FatLib\iostream.h
	Line 40: inline ostream& endl(ostream& os) {

**Comment by BennehBoy** [comment]
No luck with dev branch either:

```
In file included from C:\Users\bennehboy\Documents\Arduino\libraries\ArduinoMenu\src/menu.h:21:0,

                 from C:\Users\bennehboy\Documents\Arduino\LRDuino\LRduinoV0.01\LRDuino\LRDuino.ino:12:

C:\Users\bennehboy\Documents\Arduino\libraries\Streaming/Streaming.h:114:21: error: 'endl' redeclared as different kind of symbol

 enum _EndLineCode { endl };

                     ^

In file included from C:\Users\bennehboy\Documents\Arduino\libraries\SdFat\src/FatLib/bufstream.h:27:0,

                 from C:\Users\bennehboy\Documents\Arduino\libraries\SdFat\src/FatLib/ArduinoStream.h:29,

                 from C:\Users\bennehboy\Documents\Arduino\libraries\SdFat\src/FatLib/FatLib.h:23,

                 from C:\Users\bennehboy\Documents\Arduino\libraries\SdFat\src/SdFat.h:28,

                 from C:\Users\bennehboy\Documents\Arduino\LRDuino\LRduinoV0.01\LRDuino\LRDuino.ino:5:

C:\Users\bennehboy\Documents\Arduino\libraries\SdFat\src/FatLib/iostream.h:40:17: error: previous declaration of 'ostream& endl(ostream&)'

 inline ostream& endl(ostream& os) {

                 ^

exit status 1
```

**Comment by neu-rah** [comment]
with the dev branch of the menu?

**Comment by BennehBoy** [comment]
Tried against both nano/uno & stm32

nano/uno throws more errors, stm32 just the above

**Comment by BennehBoy** [comment]
I'm using this streaming.h -> https://github.com/scottdky/Streaming

Thought it worth checking :D

**Comment by neu-rah** [comment]
yup, do you include it on your sketch?

because the:
 #if !defined(ArduinoStream_h)
    #include <Streaming.h>
  #endif


was the instruction to not use it when we are using SdFat, but if there are other includes it will be included

**Comment by BennehBoy** [comment]
No:

#include <Adafruit_SSD1306.h>
#include <SdFat.h>
#include "LRDuinoGFX.h"
#include <Fonts/FreeSansBoldOblique12pt7b.h>
#include <Fonts/FreeSansBoldOblique24pt7b.h>
#include <Adafruit_Sensor.h>
#include <Adafruit_ADXL345_U.h>
#include <Adafruit_HMC5883_U.h>
#include <menu.h>
#include <menuIO/serialOut.h>
#include <menuIO/chainStream.h>
#include <menuIO/adafruitGfxOut.h>
#include <Buttons.h>

Also, I get the same error when compiling codectrl.ino from the examples if I include sdfat.h before menu.h

**Comment by neu-rah** [comment]
welp dev was not a good push, travis is failing all tests..please forget the dev branch, its a mess... it seems it compiles only here.

but using codeCtrl or some other example is an excellent start, this was i can put assumption about your code aside and work on the examples, i will stick with the master branch for testing...

**Comment by neu-rah** [comment]
all right! i was able to reproduce it here, by using master branch and codeCtrl with SdFat :D

at least now i have a target... and i'm on top of it :D

**Comment by BennehBoy** [comment]
cool. thanks for your efforts.

**Comment by neu-rah** [comment]
Ok, got dev branch build passing on travis, master became a mess after me merging stuff...

Removed the usage of stream (<<) from non debug code, it happens that I was using quite a lot on examples.

**Comment by neu-rah** [comment]
master branch also compiling on travis and with stream dependency removed from non-debug code and from examples

**Comment by BennehBoy** [comment]
Works!

I'll do some more testing then close this off.

Thanks you!

**Comment by BennehBoy** [comment]
sdfat library also working fine.  👍

**Comment by neu-rah** [comment]
using master branch?

**Comment by BennehBoy** [comment]
Yes

**Comment by BennehBoy** [comment]
Hey sorry to tack this on here but I couldn't think how else to ask...

Is there any way that I can dynamically generate a scrollable list of items (doesn't need to be any action other maybe a BACK) from an array/struct etc?  I think this would be a fantastic feature if somehow part of the code could be called to draw this.

Anyhow, just a thought before I try and hackjob something!

**Comment by neu-rah** [comment]
yes it would, but at moment not really. i've done some dissertations about it but not any tests yet.

about other contacts, my youtube channel has links to my facebook and G+

**Comment by lostangles** [comment]
Hey quick question since BennehBoy brought this up earlier this month and I was trying to do a similar thing.

I'm trying to read through a list of SDCard files.  Is there an example or way to do this using Arduino Menu?  I figured there was a way to iterate over an array or a list, but the above leads me to believe there isn't.  

Is there any mechanism within this library that would help with that?

**Comment by neu-rah** [comment]
the short answer: for the moment no

this is a static (PROGMEM menu) so all of its structure must be known at compile time... for mcu's that do not have PROGMEM or that simulate it with RAM as is the case of STM, Arduino due, arms, esp's, etc... the menu is then on ram.
I had some success doing dynamic creation of menu's on such systems, but its not yet clear about the integration with the API. Probably will had to do extensive classification of existing data with preprocessor conditional... or something else based of class derivation (not explored this path yet)
